### ISSUE TITLE
Not ASCII

### ISSUE THREAD

**Issue by Crissov** [samrose3/autocomplete-ascii-emoji#1]
Um, you got Eastern _kaomoji_ there, while “ASCII emoji” suggests Western sideways emoticons. See for instance <http://en.wikipedia.org/wiki/List_of_emoticons>.

**Comment by sam-b-rose** [comment]
@Crissov Ah yeah, you are right. Good catch! I didn't even think about that. I'll rename it to `autocomplete-kaomoji` if that doesn't already exist ¯\\_(ツ)_/¯

Thank you!
